# Generated by Django 5.2.7 on 2025-11-06 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название клуба')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('founded', models.IntegerField(verbose_name='Год основания')),
                ('stadium', models.CharField(max_length=100, verbose_name='Стадион')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Логотип')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.club', verbose_name='Клуб')),
            ],
        ),
    ]
